# Generated by Django 4.0.4 on 2022-05-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('summery', models.TextField(blank=True, max_length=1000, null=True)),
                ('school', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('previous_work', models.CharField(blank=True, max_length=255, null=True)),
                ('skills', models.TextField(max_length=1000)),
            ],
        ),
    ]
