# Generated by Django 4.0.4 on 2022-05-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0004_alter_profile_school_alter_profile_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='previous_work',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
